import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const keifont = localFont({
  src: "../../public/fonts/keifont.ttf",
  variable: "--font-kei",
});

const hanazomefont = localFont({
  src: "../../public/fonts/hanazomefont.ttf",
  variable: "--font-hanazome",
});

export const metadata: Metadata = {
  title: "ナンバートーク",
  description: "Generated by ナンバートーク",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        geistSans.variable,
        geistMono.variable,
        keifont.variable,
        hanazomefont.variable,
        "h-full antialiased",
      )}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
