import {
  TbAffiliateFilled,
  TbAlpha,
  TbAppleFilled,
  TbAlienFilled,
  TbAlertSquareFilled,
  TbArcheryArrow,
  TbAtom,
  TbAwardFilled,
  TbBadgeFilled,
  TbBaguette,
  TbBalloonFilled,
  TbBallBasketball,
  TbBallFootball,
  TbBallAmericanFootball,
  TbBallVolleyball,
  TbBallBowling,
  TbBoltFilled,
  TbBongFilled,
  TbBoneFilled,
  TbBombFilled,
  TbBox,
  TbBrandGithubFilled,
  TbBrandSnapchatFilled,
  TbBrush,
  TbCactusFilled,
  TbCake,
  TbCampfireFilled,
  TbCarambolaFilled,
  TbCardboardsFilled,
  TbChartPie2Filled,
  TbCherryFilled,
  TbChessKnightFilled,
  TbChessKingFilled,
  TbChristmasTreeFilled,
  TbClipboardPlusFilled,
  TbCloverFilled,
  TbCookieManFilled,
  TbDeviceTvFilled,
  TbEggCrackedFilled,
  TbEyeglassFilled,
  TbFeatherFilled,
  TbFlask2Filled,
  TbGlassFilled,
  TbHeartFilled,
  TbHelicopterFilled,
  TbJewishStarFilled,
  TbKeyFilled,
  TbPigFilled,
  TbSeedlingFilled,
  TbShieldHalfFilled,
  TbSnowflake,
  TbSpadeFilled,
  TbSnowman,
  TbSpiderFilled,
  TbSpeedboatFilled,
  TbTax,
  TbTrophyFilled,
  TbUmbrellaFilled,
  TbYinYangFilled,
  TbZeppelinFilled,
  TbZoomFilled,
  TbTruckFilled,
  TbUfoFilled,
  TbStarFilled,
  TbSoupFilled,
} from "react-icons/tb";

export const AVAILABLE_ICONS = [
  { id: "alien", Icon: TbAlienFilled, color: "text-teal-800", label: "宇宙人" },
  {
    id: "apple",
    Icon: TbAppleFilled,
    color: "text-slate-800",
    label: "りんご",
  },
  { id: "star", Icon: TbStarFilled, color: "text-indigo-800", label: "星" },
  {
    id: "heart",
    Icon: TbHeartFilled,
    color: "text-violet-800",
    label: "ハート",
  },
  {
    id: "ghost",
    Icon: TbAffiliateFilled,
    color: "text-purple-900",
    label: "シンボル",
  },
  {
    id: "cactus",
    Icon: TbCactusFilled,
    color: "text-emerald-800",
    label: "サボテン",
  },
  {
    id: "cherry",
    Icon: TbCherryFilled,
    color: "text-zinc-800",
    label: "さくらんぼ",
  },
  {
    id: "clover",
    Icon: TbCloverFilled,
    color: "text-green-800",
    label: "クローバー",
  },
  {
    id: "cookie",
    Icon: TbCookieManFilled,
    color: "text-cyan-900",
    label: "クッキー",
  },
  { id: "pig", Icon: TbPigFilled, color: "text-fuchsia-800", label: "ぶた" },
  {
    id: "seedling",
    Icon: TbSeedlingFilled,
    color: "text-teal-700",
    label: "ふたば",
  },
  { id: "snowman", Icon: TbSnowman, color: "text-blue-700", label: "雪だるま" },
  {
    id: "snowflake",
    Icon: TbSnowflake,
    color: "text-sky-700",
    label: "雪の結晶",
  },
  {
    id: "trophy",
    Icon: TbTrophyFilled,
    color: "text-indigo-700",
    label: "トロフィー",
  },
  { id: "award", Icon: TbAwardFilled, color: "text-cyan-800", label: "勲章" },
  { id: "badge", Icon: TbBadgeFilled, color: "text-blue-800", label: "バッジ" },
  {
    id: "balloon",
    Icon: TbBalloonFilled,
    color: "text-purple-800",
    label: "風船",
  },
  {
    id: "bolt",
    Icon: TbBoltFilled,
    color: "text-slate-800",
    label: "カミナリ",
  },
  { id: "bomb", Icon: TbBombFilled, color: "text-gray-900", label: "爆弾" },
  { id: "bone", Icon: TbBoneFilled, color: "text-zinc-700", label: "ほね" },
  {
    id: "campfire",
    Icon: TbCampfireFilled,
    color: "text-indigo-900",
    label: "焚き火",
  },
  {
    id: "carambola",
    Icon: TbCarambolaFilled,
    color: "text-teal-900",
    label: "スターフルーツ",
  },
  {
    id: "christmas_tree",
    Icon: TbChristmasTreeFilled,
    color: "text-emerald-900",
    label: "ツリー",
  },
  {
    id: "egg",
    Icon: TbEggCrackedFilled,
    color: "text-cyan-700",
    label: "割れた卵",
  },
  {
    id: "flask",
    Icon: TbFlask2Filled,
    color: "text-violet-900",
    label: "フラスコ",
  },
  { id: "glass", Icon: TbGlassFilled, color: "text-sky-800", label: "グラス" },
  { id: "key", Icon: TbKeyFilled, color: "text-slate-700", label: "鍵" },
  {
    id: "spade",
    Icon: TbSpadeFilled,
    color: "text-neutral-900",
    label: "スペード",
  },
  { id: "spider", Icon: TbSpiderFilled, color: "text-black", label: "クモ" },
  {
    id: "umbrella",
    Icon: TbUmbrellaFilled,
    color: "text-blue-900",
    label: "傘",
  },
  { id: "ufo", Icon: TbUfoFilled, color: "text-indigo-600", label: "UFO" },
  { id: "soup", Icon: TbSoupFilled, color: "text-teal-800", label: "スープ" },
  { id: "cake", Icon: TbCake, color: "text-fuchsia-900", label: "ケーキ" },
  {
    id: "baguette",
    Icon: TbBaguette,
    color: "text-cyan-800",
    label: "バゲット",
  },
  {
    id: "basketball",
    Icon: TbBallBasketball,
    color: "text-slate-800",
    label: "バスケ",
  },
  {
    id: "football",
    Icon: TbBallFootball,
    color: "text-neutral-800",
    label: "サッカー",
  },
  {
    id: "american_football",
    Icon: TbBallAmericanFootball,
    color: "text-zinc-900",
    label: "アメフト",
  },
  {
    id: "volleyball",
    Icon: TbBallVolleyball,
    color: "text-indigo-800",
    label: "バレー",
  },
  {
    id: "bowling",
    Icon: TbBallBowling,
    color: "text-purple-800",
    label: "ボウリング",
  },
  {
    id: "truck",
    Icon: TbTruckFilled,
    color: "text-blue-800",
    label: "トラック",
  },
  {
    id: "helicopter",
    Icon: TbHelicopterFilled,
    color: "text-slate-900",
    label: "ヘリコプター",
  },
  {
    id: "speedboat",
    Icon: TbSpeedboatFilled,
    color: "text-cyan-900",
    label: "ボート",
  },
  {
    id: "zeppelin",
    Icon: TbZeppelinFilled,
    color: "text-emerald-800",
    label: "飛行船",
  },
  {
    id: "chess_knight",
    Icon: TbChessKnightFilled,
    color: "text-neutral-700",
    label: "ナイト",
  },
  {
    id: "chess_king",
    Icon: TbChessKingFilled,
    color: "text-zinc-800",
    label: "キング",
  },
  { id: "brush", Icon: TbBrush, color: "text-teal-700", label: "筆" },
  {
    id: "feather",
    Icon: TbFeatherFilled,
    color: "text-slate-600",
    label: "羽",
  },
  { id: "box", Icon: TbBox, color: "text-indigo-900", label: "箱" },
  {
    id: "cardboards",
    Icon: TbCardboardsFilled,
    color: "text-cyan-800",
    label: "段ボール",
  },
  { id: "tv", Icon: TbDeviceTvFilled, color: "text-zinc-700", label: "テレビ" },
  {
    id: "eyeglass",
    Icon: TbEyeglassFilled,
    color: "text-gray-800",
    label: "メガネ",
  },
  { id: "atom", Icon: TbAtom, color: "text-sky-700", label: "原子" },
  {
    id: "yinyang",
    Icon: TbYinYangFilled,
    color: "text-neutral-800",
    label: "陰陽",
  },
  {
    id: "jewish_star",
    Icon: TbJewishStarFilled,
    color: "text-blue-900",
    label: "ダビデの星",
  },
  {
    id: "archery",
    Icon: TbArcheryArrow,
    color: "text-slate-800",
    label: "アーチェリー",
  },
  {
    id: "github",
    Icon: TbBrandGithubFilled,
    color: "text-neutral-900",
    label: "GitHub",
  },
  {
    id: "snapchat",
    Icon: TbBrandSnapchatFilled,
    color: "text-zinc-800",
    label: "Snapchat",
  },
  {
    id: "chart_pie",
    Icon: TbChartPie2Filled,
    color: "text-indigo-800",
    label: "グラフ",
  },
  {
    id: "clipboard",
    Icon: TbClipboardPlusFilled,
    color: "text-slate-700",
    label: "クリップボード",
  },
  {
    id: "shield",
    Icon: TbShieldHalfFilled,
    color: "text-blue-800",
    label: "盾",
  },
  { id: "zoom", Icon: TbZoomFilled, color: "text-zinc-700", label: "虫眼鏡" },
  {
    id: "alert",
    Icon: TbAlertSquareFilled,
    color: "text-teal-900",
    label: "警告",
  },
  { id: "tax", Icon: TbTax, color: "text-emerald-900", label: "税金" },
  { id: "alpha", Icon: TbAlpha, color: "text-violet-800", label: "アルファ" },
  { id: "bong", Icon: TbBongFilled, color: "text-green-800", label: "ボン" },
];
